# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:23
'''
added by chap 10 Revisiting Migrations pg 279.
 whole purpose is backend db modifications over time, as new functionality, bug fixes implemented
 this acts somewhat as version control on the ORM/database- see pg 284.
 and can implement new db functions over time- which is why django builds in the format 0001,0002 etc.


08/20/17- Note I did not implement all the migrations in the book, or change newslink to include a slug field
I established this 1st script via cmd line and made sure web app still started.
note the add and remove functions are not fleshed out or called in 'operations' method below in this basic version.

may end up revisiting this in future chapters.
'''
from __future__ import unicode_literals

from django.db import migrations


def add_tag_data(apps, schema_editor):
    pass


def remove_tag_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
    ]
